apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  labels:
    purpose: jenkins-shared-deployement
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {$NFS_HOST}
    path: "/opt/jenkins"