apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ibm-cloud-ingress
spec:
  rules:
    - host: "demo-ibm-cloud.pj.chmstore.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: demo-ibm-cloud
                port:
                  number: 80
    - host: "demo-ibm-cloud-test.pj.chmstore.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: demo-ibm-cloud-test
                port:
                  number: 80